// Generated by https://quicktype.io

export interface User {
	data: Data;
}

export interface Data {
	attributes: Attributes;
	id: string;
	links: Links;
	type: string;
}

export interface Attributes {
	apikey: string;
	email: string;
	first_name: string;
	has_2fa: boolean;
	last_login: number;
	last_name: string;
	preferences: Preferences;
	privileges: Privileges;
	profile_phrase: string;
	quotas: Quotas;
	reputation: number;
	status: string;
	user_since: number;
}

export interface Preferences {
	graph: Graph;
	ui: UI;
}

export interface Graph {
	dashboard_walkthrough_version_seen: string;
	last_visit: number;
	main_walkthrough_version_seen: string;
	search_tooltip_version_seen: string;
}

export interface UI {
	last_read_notification_date: number;
}

export interface Privileges {
	admin: Admin;
	allinfo: Admin;
	'big-files': BigFiles;
	cases: BigFiles;
	click_to_accept: Admin;
}

export interface Admin {
	granted: boolean;
}

export interface BigFiles {
	expiration_date?: number;
	granted: boolean;
	inherited_from: string;
	inherited_via: string;
}

export interface Quotas {
	api_requests_daily: APIRequestsDaily;
	api_requests_hourly: APIRequestsDaily;
	api_requests_monthly: APIRequestsDaily;
	cases_creation_monthly: APIRequestsDaily;
	intelligence_downloads_monthly: APIRequestsDaily;
}

export interface APIRequestsDaily {
	allowed: number;
	used: number;
}

export interface Links {
	self: string;
}
